import React, { useState } from "react";
import Head from "next/head";
import Button from "../components/Button";
import Form from "../components/Form";

export default function Home() {
  const [array, setArray] = useState([
    {
      type: "header",
      inputFields: [
        {
          label: "Product",
          value: "",
          style: "text-sm m-4 underline inline max-w-max",
        },
        {
          label: "Resources",
          value: "",
          style: "text-sm m-4 underline inline max-w-max",
        },
        {
          label: "Pricing",
          value: "",
          style: "text-sm m-4 underline inline max-w-max",
        },
      ],
    },
    {
      type: "hero",
      inputFields: [
        {
          label: "Welcome on my website",
          value: "",
          style: "text-8xl font-bold",
        },
        {
          label: "Deliver transparent web-readiness",
          value: "",
          style: "text-4xl mt-4 text-base text-slate-700 font-normal",
        },
      ],
    },
    {
      type: "content",
      inputFields: [
        {
          label: "Content disintermediate visionary functionalities",
          value: "",
          style: "text-4xl mt-4 font-extrabold tracking-tight text-slate-900",
        },
        {
          label:
            "We've built an innovative approach that utilizes cross-platform viral AI and machine learning to revolutionize your bullshit generating experience. We've built an innovative approach that utilizes cross-platform viral AI and machine learning to revolutionize your bullshit generating experience.",
          value: "",
          style: "mt-4 text-base leading-7 text-slate-700 font-normal",
        },
      ],
    },
    {
      type: "footer",
      inputFields: [
        {
          label: "Footer",
          value: "",
          style: "text-4xl mt-4 font-extrabold tracking-tight text-slate-900",
        },
      ],
    },
  ]);
  const [counter, setCounter] = useState(0);
  const [isEditView, setEditView] = useState(false);

  const addComponent = () => {
    array.push({
      inputFields: [
        {
          label: `New title`,
          value: "",
          style: "text-4xl mt-4 font-extrabold tracking-tight text-slate-900",
        },
        {
          label:
            "The Bullshit Generator is an innovative tool that utilizes cross-platform viral AI  bullshit generati",
          value: "",
          style: "mt-4 text-base leading-7 text-slate-700 font-normal",
        },
      ],
    });
    setCounter(counter + 1);
    setArray([...array]);
  };

  const remove = (index) => {
    array.splice(index, 1);
    setCounter(counter - 1);
    setArray([...array]);
  };

  const moveUp = (index) => {
    if (index === 0) {
      return;
    }

    const itemAtIndex = array[index];

    array.splice(index, 1, array[index - 1]);
    array.splice(index - 1, 1, itemAtIndex);

    setArray([...array]);
  };

  const moveDown = (index) => {
    if (index === array.length - 1) {
      return;
    }

    const itemAtIndex = array[index];

    array.splice(index, 1, array[index + 1]);
    array.splice(index + 1, 1, itemAtIndex);

    setArray([...array]);
  };

  const sectionStyle = (type) => {
    if (type === "header") {
      return "h-20  border-b flex items-center";
    } else if (type === "hero") {
      return "h-80";
    } else if (type === "content") {
      return "h-60";
    } else if (type === "footer") {
      return "h-32 border-t";
    } else {
      return "h-32";
    }
  };
  return (
    <div className="">
      <Head>
        <title>~ The Original ~</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="">
          {array.map((a, componentIndex) => (
            <div
              key={componentIndex}
              className={`${sectionStyle(a.type)} w-full px-6`}
            >
              {array[componentIndex].inputFields && (
                <Form
                  order={componentIndex}
                  array={array}
                  isEditView={isEditView}
                />
              )}
              {isEditView && (
                <div className="absolute z-10 right-0 space-x-2">
                  <Button onClick={() => moveUp(componentIndex)}>↑</Button>
                  <Button onClick={() => moveDown(componentIndex)}>↓</Button>
                  <Button onClick={() => remove(componentIndex)} color="red">
                    -
                  </Button>
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="">
          <button
            title="Edit page"
            onClick={() => setEditView(!isEditView)}
            className="fixed z-90 bottom-10 right-8 bg-black w-20 h-20 rounded-full drop-shadow-lg flex justify-center items-center text-white text-4xl hover:bg-blue-700 hover:drop-shadow-2xl"
          >
            &#9998;
          </button>
          <button
            title="Add component"
            onClick={addComponent}
            className="fixed z-90 bottom-10 right-32 bg-blue-600 w-20 h-20 rounded-full drop-shadow-lg flex justify-center items-center text-white text-4xl hover:bg-blue-700 hover:drop-shadow-2xl"
          >
            &#43;
          </button>
        </div>
      </main>
    </div>
  );
}
