import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import Input from "../components/Input";

export default function Home() {
  const [array, setArray] = useState([
    {
      title: "Hello I'm the 1st component",
      inputFields: [
        { label: "Title", value: "" },
        { label: "Subtitle", value: "" },
      ],
    },
    {
      title: "Hello I'm the 2nd component",
      inputFields: [
        { label: "Title", value: "" },
        { label: "Subtitle", value: "" },
      ],
    },
    { title: "Hello I'm the 3rd component" },
  ]);
  const [counter, setCounter] = useState(0);
  const [title, setTitle] = useState("");

  const addComponent = () => {
    array.push({ title: `added component ${counter}` });
    setCounter(counter + 1);
    setArray([...array]);
  };

  const remove = (index) => {
    array.splice(index, 1);
    setCounter(counter - 1);
    setArray([...array]);
  };

  const moveUp = (index) => {
    if (index === 0) {
      return;
    }

    const itemAtIndex = array[index];

    array.splice(index, 1, array[index - 1]);
    array.splice(index - 1, 1, itemAtIndex);

    setArray([...array]);
  };

  const moveDown = (index) => {
    if (index === array.length - 1) {
      return;
    }

    const itemAtIndex = array[index];

    array.splice(index, 1, array[index + 1]);
    array.splice(index + 1, 1, itemAtIndex);

    setArray([...array]);
  };

  const handleChange = (e) => {
    console.log(e.target.value, "e");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Reusable landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="p-8">
          <Button onClick={addComponent} color="green">
            Add component +
          </Button>
        </div>

        <div>
          {array.map((a, index) => (
            <div key={index} className="m-6 font-bold">
              <p className="text-2xl">{a.title}</p>

              {a.inputFields &&
                a.inputFields.map((input, i) => (
                  <Input
                    key={i}
                    placeholder={input.label}
                    id={i}
                    type="text"
                    onChange={handleChange}
                    // onChange={(e) => setTitle(e.target.title)}
                  />
                ))}

              {/* <input
                type="text"
                value={a.title}
                onChange={(e) => setTitle(e.target.title)}
              /> */}

              <Button onClick={() => moveUp(index)}>Move Up ↑</Button>
              <Button onClick={() => moveDown(index)}>Move Down ↓</Button>
              <Button onClick={() => remove(index)} color="red">
                Delete -
              </Button>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
